
POST http://localhost:8080/match
Content-Type: application/json

{
    "home_team": {
      "player_one": {
        "first_name": "PlayerOne",
        "last_name": "Home"
      },
      "player_two": {
        "first_name": "PlayerTwo",
        "last_name": "Home"
      }
    },
    "opposing_team": {
      "player_one": {
        "first_name": "PlayerOne",
        "last_name": "Opposing"
      },
      "player_two": {
        "first_name": "PlayerTwo",
        "last_name": "Opposing"
      }
    },
    "score": {
      "home_team_score": 9,
      "opposing_team_score": 7
    }
  }

###
PUT http://localhost:8080/match/1
Content-Type: application/json

{
  "home_team": {
    "player_one": {
      "id": 1,
      "first_name": "PlayerOneUpdated",
      "last_name": "Home"
    },
    "player_two": {
      "first_name": "PlayerTwo",
      "last_name": "Home"
    }
  },
  "opposing_team": {
    "player_one": {
      "first_name": "PlayerOne",
      "last_name": "Opposing"
    },
    "player_two": {
      "id": 2,
      "first_name": "PlayerTwoUpdated",
      "last_name": "Opposing"
    }
  },
  "score": {
    "home_team_score": 9,
    "opposing_team_score": 7
  }
}


###

POST http://localhost:8080/match
Content-Type: application/json

{
    "id": 1
}

###

POST http://localhost:8080/match
Content-Type: application/json

{
  "match": {
    "id": 1,
    "created_date": "1995-01-01T00:00:00Z"
  }}


###
GET http://localhost:8080/match
Accept: application/json

